# Generated by Django 4.1.3 on 2022-12-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('imagen', models.CharField(default='https://i.blogs.es/87930e/comidas-ricas/1366_2000.jpg', max_length=120)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ingredientes', models.JSONField()),
                ('preparacion', models.JSONField()),
            ],
            options={
                'ordering': ['creado'],
            },
        ),
    ]
